### ISSUE TITLE
Dependency on NLog

### ISSUE THREAD

**Issue by jfloodnet** [flexmonster/pivot-accelerator-dll#1]
Hi,

Please remove the dependency on NLog and replace with https://github.com/damianh/LibLog

Also, a nuget package would be welcomed.

Cheers,
Joe

**Comment by flexmonster** [comment]
Hello,
Thank you for your question. Could please specify what issues you have with the NLog?
The idea with a NuGet package sounds reasonable and we will add it to our backlog.
Waiting for the update from you.
Regards,
Flexmonster team

**Comment by jfloodnet** [comment]
Hi - the issue is I don't want a dependency on NLog. I use a different logger and multiple loggers is not desirable. If you use LibLog - then it's all taken care of.

**Comment by flexmonster** [comment]
Hello Joe,

It's clear, we will remove the dependency in the next update (ETA Aug 27).

Regards,
Flexmonster team

**Comment by jfloodnet** [comment]
thanks!

**Comment by flexmonster** [comment]
Hello Joe,
We have updated the Flexmonster.Accelerator dll and now it does not include Nlog dependence. Also, for now it is possible to set your own logger. The new logger should implement the Accelerator.Utils.ILogger interface. Here is the example of how you can set your own logger:
`Accelerator.Utils.LoggerLocator.SetLogger(new Logger());`
Also, in the nearest time we will add the package to the NuGet.
Please let us know in case of any other question.
Regards,
Flexmonster team

**Comment by flexmonster** [comment]
Hello Joe, 
We are glad to inform you that the accelerator .dll is now available on the NuGet. You are welcome to try it [here](https://www.nuget.org/packages/Flexmonster.Accelerator/).
Please let us know if everything works fine for you.
Regards,
Flexmonster team
