### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by shahztechfarm** [flexmonster/pivot-accelerator-dll#2]
Please upload a license file for the repository. This will help clarifying the licensing questions.

**Comment by VeraDidenko** [comment]
Hello, @shahjahan-tapadar,

Thank you for writing to us.

We added an MIT license file for the repository.
Please note that this repository holds the source code for a sample project using Flexmonster Accelerator as a DLL.
With this in mind, the sample project is under an MIT license, but Flexmonster and Flexmonster Accelerator DLL are under a custom license. For more details, please see: [https://www.flexmonster.com/terms/Flexmonster-Software-License-Agreement.pdf](https://www.flexmonster.com/terms/Flexmonster-Software-License-Agreement.pdf).

Kind regards,
Vera
